language: java
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 59bf1662-c4e9-41dc-b583-b636ffeddd92
  - mvn jacoco:report coveralls:report
notifications:
  slack: analyzeme:2nmw8U7mQ58mlNHlWnsqvYXI
