codecov:
  token: 59bf1662-c4e9-41dc-b583-b636ffeddd92
  branch: master
  bot: null
comment:
  layout: header, changes, diff, sunburst
coverage:
  precision: 0
  round: down
  range: "30...80"
  status:
    patch:
      default:
        target: '30'
    project:
      default:
        target: auto
